"""
Django settings for petpals project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-to9rm2l7%fr52@7r*a0)54f^i!ex!6i_lbqqvur43g#qe-89i$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['s4f43958.natappfree.cc', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.pets',
    'apps.users',
    'apps.services',
    'apps.orders',
    'apps.products',
    'apps.community',
    'apps.cart',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'petpals.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tools.context_processors.cart_item_count',
                'tools.context_processors.cart_item_kind',
            ],
        },
    },
]

WSGI_APPLICATION = 'petpals.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# myproject/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'petpals',
        'USER': 'root',
        'PASSWORD': 'yang123.',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            # 确保连接使用utf8mb4编码（支持emoji）
            'charset': 'utf8mb4',
            # 可选：设置连接超时时间（秒）
            'connect_timeout': 10,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


MEDIA_URL = '/media/'  # 媒体文件的URL前缀
MEDIA_ROOT = BASE_DIR / 'media'  # 媒体文件存储的物理路径

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

# 支付宝沙箱配置
ALIPAY_SETTINGS = {
    "appid": "9021000155669214",
    "app_return_url": "http://s4f43958.natappfree.cc/pay/success/",    # 同步回调地址
    "app_notify_url": "http://s4f43958.natappfree.cc/alipay/notify/",  # 异步回调地址
    "app_private_key_path": os.path.join(BASE_DIR, "keys/app_private_key.pem"),  # 应用私钥路径
    "alipay_public_key_path": os.path.join(BASE_DIR, "keys/alipay_public_key.pem"),  # 支付宝公钥路径
    "sign_type": "RSA2",  # 签名方式
    "debug": True,  # 沙箱环境为True
}

# 读取密钥内容
from Crypto.PublicKey import RSA
# 1. 读取应用私钥
with open(ALIPAY_SETTINGS['app_private_key_path'], 'r') as f:
    app_private_key_content = f.read()
    private_key = RSA.import_key(app_private_key_content) # 主要是对文件内容进行处理，移除空格，换行，以及类似-----BEGIN PUBLIC KEY-----的样式
    app_private_key = private_key.export_key().decode('utf-8')
    ALIPAY_SETTINGS['app_private_key'] = app_private_key
# 2. 读取支付宝公钥
with open(ALIPAY_SETTINGS['alipay_public_key_path'], 'r') as f:
    alipay_public_key_content = f.read()
    public_key = RSA.import_key(alipay_public_key_content)
    alipay_public_key = public_key.export_key().decode('utf-8')
    ALIPAY_SETTINGS['alipay_public_key'] = alipay_public_key